dataset:
  mnistcifar:
    num_classes: 2
  name: mnist
distributed:
  data_seed: 202
  num_samples: '32'
  permutation_seed: 202
model:
  arch: lenet
  init: uniform02
  lenet:
    width: 3/6
  model_count_times_batch_size: 800000
optimizer:
  name: guess
output:
  folder: output/mnist/mnist_202_202_lenet_guess_uniform02_width05_32samples
  load_models_from_previous_num_of_samples: true
  save_predictions: true
  save_weights: true
  successful_model_count: 2000
