dataset:
  mnistcifar:
    num_classes: 2
  name: mnist
distributed:
  data_seed: 202
  num_samples: 2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,100,102,104,106,108,110,112,114,116,118,120,122,124,126,128
  permutation_seed: 200
model:
  arch: lenet
  init: uniform
  lenet:
    width: 2/6
  model_count_times_batch_size: 1000000
optimizer:
  name: guess
output:
  folder: output/mnist/long_mnist_202_200_lenet_guess_uniform_width033_multi_samples
  load_models_from_previous_num_of_samples: true
  save_predictions: true
  save_weights: true
  successful_model_count: 100
