dataset:
  mnistcifar:
    num_classes: 2
  name: cifar10
distributed:
  data_seed: 219
  num_samples: 2,4,6,8,10,12,14,16,18,20,22,24
  permutation_seed: 203
model:
  arch: lenet
  init: uniform
  lenet:
    width:
    - 1/6
    - 1/6
    - 1/24
    - 1/24
  model_count_times_batch_size: 1000000
optimizer:
  name: guess
output:
  folder: output/cifar10/cifar_219_203_lenet_guess_uniform_width0165x2_01x2_multi_samples
  load_models_from_previous_num_of_samples: true
  save_predictions: true
  save_weights: true
  successful_model_count: 100
