dataset:
  mnistcifar:
    num_classes: 2
  name: cifar10
distributed:
  data_seed: 201
  num_samples: 2,4,6,8,10,12,14,16,18,20,22,24
  permutation_seed: 200
model:
  arch: lenet
  init: uniform
  lenet:
    width: 1
  model_count_times_batch_size: 200000
optimizer:
  name: guess
output:
  folder: output/cifar10/cifar_201_200_lenet_guess_uniform_width1_multi_samples
  load_models_from_previous_num_of_samples: true
  save_predictions: true
  save_weights: true
  successful_model_count: 100
