dataset:
  mnistcifar:
    num_classes: 2
  name: cifar10
distributed:
  data_seed: 201
  num_samples: '16'
  permutation_seed: 201
model:
  arch: lenet
  init: uniform
  lenet:
    conv_layers: 0,1
    fc_layers: 0,1,2
    width: 2/6
  model_count_times_batch_size: 1000000
optimizer:
  name: guess
output:
  folder: output/cifar10/cifar_201_201_lenet_guess_uniform_width033_16samples
  load_models_from_previous_num_of_samples: true
  save_predictions: true
  save_weights: true
  successful_model_count: 500
