dataset:
  mnistcifar:
    num_classes: 2
  name: cifar10
distributed:
  data_seed: 219
  num_samples: '16'
  permutation_seed: 201
model:
  arch: lenet
  init: kaiming
  lenet:
    width: 3/6
  model_count_times_batch_size: 800000
optimizer:
  name: guess
output:
  folder: output/cifar10/cifar_219_201_lenet_guess_kaiming_width05_16samples
  load_models_from_previous_num_of_samples: true
  save_predictions: true
  save_weights: true
  successful_model_count: 500
