dataset:
  mnistcifar:
    num_classes: 2
  name: cifar10
distributed:
  data_seed: 201
  num_samples: 2,4,6,8,10,12,14,16,18,20,22,24,400
  permutation_seed: 200
model:
  arch: mlp
  batch_size: 2
  init: kaiming
  lenet:
    fc_layers: 0,1,2,3,4
    pooling_layers: 0
    width: 1/6
  model_count_times_batch_size: 200
optimizer:
  epochs: 60
  lr: 0.01
  name: SGD
output:
  folder: output/cifar10/cifar_201_200_mlp_sgd_kaiming_lr01_epoch60_width0165_multi_samples
  load_models_from_previous_num_of_samples: false
  save_predictions: true
  save_weights: true
  successful_model_count: 100
