dataset:
  mnistcifar:
    num_classes: 2
  name: mnist
distributed:
  data_seed: 204
  num_samples: '16'
  permutation_seed: 202
model:
  arch: lenet
  init: uniform
  lenet:
    width: 2/6
  model_count_times_batch_size: 1000000
optimizer:
  name: guess
output:
  folder: output/mnist/mnist_204_202_lenet_guess_uniform_width033_16samples
  load_models_from_previous_num_of_samples: true
  save_predictions: true
  save_weights: true
  successful_model_count: 500
