dataset:
  mnistcifar:
    num_classes: 2
  name: cifar10
distributed:
  data_seed: 201
  num_samples: 2,4,6,8,10,12,14,16,18,20,22,24
  permutation_seed: 203
model:
  arch: lenet_more_layers
  init: uniform
  lenet:
    conv_layers: 0
    fc_layers: 2
    width: 2/6
  model_count_times_batch_size: 1000000
optimizer:
  name: guess
output:
  folder: output/cifar10/cifar_201_203_lenet_guess_uniform_width033_1c-1f_multi_samples
  load_models_from_previous_num_of_samples: true
  save_predictions: true
  save_weights: true
  successful_model_count: 100
