dataset:
  mnistcifar:
    num_classes: 2
  name: mnist
distributed:
  data_seed: 204
  num_samples: '16'
  permutation_seed: 202
model:
  arch: lenet
  batch_size: 2
  init: uniform02
  lenet:
    width: 3/6
  model_count_times_batch_size: 1000
optimizer:
  epochs: 60
  lr: 0.01
  name: SGD
output:
  folder: output/mnist/mnist_204_202_lenet_sgd_uniform02_lr01_epoch60_width05_16samples
  load_models_from_previous_num_of_samples: false
  save_predictions: true
  save_weights: true
  successful_model_count: 500
